chat/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.lobby, name='lobby'),
    path('room/', views.room, name='chat-room'),
    path('get_token/', views.getToken),

    path('create_member/', views.createMember),
    path('get_member/', views.getMember),
    path('delete_member/', views.deleteMember),
]

study_space/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users.views import UserProfile
from classroom.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('course/', include('classroom.urls')),
    path('chat/', include('chat.urls')),
    path('direct/', include('direct.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('user/<username>/', UserProfile, name='profile'),
    path('', index, name='index')
   
]
if settings.DEBUG:
    urlpatterns  += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/models.py
from django.db import models
from django.contrib.auth.models import User

#3rd apps field
from ckeditor.fields import RichTextField

# Create your models here.

class Answer(models.Model):
	answer_text = models.CharField(max_length=900)
	is_correct = models.BooleanField(default=False)
	user = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return self.answer_text

class Question(models.Model):
	question_text = models.CharField(max_length=900)
	answers = models.ManyToManyField(Answer)
	points = models.PositiveIntegerField()
	user = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return self.question_text

class Quizzes(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=200)
	description = RichTextField()
	date = models.DateTimeField(auto_now_add=True)
	due = models.DateField()
	allowed_attempts = models.PositiveIntegerField()
	time_limit_mins = models.PositiveIntegerField()
	questions = models.ManyToManyField(Question)

	def __str__(self):
		return self.title

class Attempter(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	quiz = models.ForeignKey(Quizzes, on_delete=models.CASCADE)
	score = models.PositiveIntegerField()
	completed = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.user.username

class Attempt(models.Model):
	quiz = models.ForeignKey(Quizzes, on_delete=models.CASCADE)
	attempter = models.ForeignKey(Attempter, on_delete=models.CASCADE)
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	answer = models.ForeignKey(Answer, on_delete=models.CASCADE)

	def __str__(self):
		return self.attempter.user.username + ' - ' + self.answer.answer_text


quiz/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from .models import Question, Quizzes, Answer


class NewQuizForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'validate'}), required=True)    
    description = forms.CharField(widget=CKEditorWidget)
    due = forms.DateField(widget=forms.TextInput(attrs={'class': 'datepicker'}), required=True)    
    allowed_attempts = forms.IntegerField(max_value=100, min_value=1)
    time_limit_mins = forms.IntegerField(max_value=360, min_value=10)

    class Meta:
        model = Quizzes
        fields = ['title', 'description', 'due', 'allowed_attempts', 'time_limit_mins' ]
    
class NewQuestionForm(forms.ModelForm):
    question_text = forms.CharField(widget=forms.TextInput(attrs={'class': 'validate'}), required=True)
    points = forms.IntegerField(max_value=100, min_value=1)    

    class Meta:
        model = Question
        fields = ['question_text', 'points',]


quiz/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseForbidden

from django.contrib.auth.decorators import login_required

from .forms import NewQuestionForm, NewQuizForm
from .models import Answer, Quizzes, Question, Attempter, Attempt
from module.models import Module
from completion.models import Completion

# Create your views here.


def NewQuiz(request, course_id, module_id):
    user = request.user
    module = get_object_or_404(Module, id=module_id)
    if request.method == 'POST':
        form = NewQuizForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            description = form.cleaned_data.get('description')
            due = form.cleaned_data.get('due')
            allowed_attempts = form.cleaned_data.get('allowed_attempts')
            time_limit_mins = form.cleaned_data.get('time_limit_mins')
            quiz = Quizzes.objects.create(user=user, title=title, description=description,
                                          due=due, allowed_attempts=allowed_attempts, time_limit_mins=time_limit_mins)
            module.quizzes.add(quiz)
            module.save()
            return redirect('new-question', course_id=course_id, module_id=module_id, quiz_id=quiz.id)
    else:
        form = NewQuizForm()

    context = {
        'form': form,
    }
    return render(request, 'quiz/new-quiz.html', context)


def NewQuestion(request, course_id, module_id, quiz_id):
    user = request.user
    quiz = get_object_or_404(Quizzes, id=quiz_id)
    if request.method == 'POST':
        form = NewQuestionForm(request.POST)
        if form.is_valid():
            question_text = form.cleaned_data.get('question_text')
            points = form.cleaned_data.get('points')
            answer_text = request.POST.getlist('answer_text')
            is_correct = request.POST.getlist('is_correct')

            question = Question.objects.create(
                question_text=question_text, user=user, points=points)

            for a, c in zip(answer_text, is_correct):
                answer = Answer.objects.create(
                    answer_text=a, is_correct=c, user=user)
                question.answers.add(answer)
                question.save()
                quiz.questions.add(question)
                quiz.save()
            return redirect('new-question', course_id=course_id, module_id=module_id, quiz_id=quiz.id)
    else:
        form = NewQuestionForm()

    context = {
        'form': form,
    }
    return render(request, 'quiz/new-question.html', context)


def QuizDetail(request, course_id, module_id, quiz_id):
    user = request.user
    quiz = get_object_or_404(Quizzes, id=quiz_id)
    my_attempts = Attempter.objects.filter(quiz=quiz, user=user)

    context = {
        'quiz': quiz,
        'my_attempts': my_attempts,
        'course_id': course_id,
        'module_id': module_id,
    }
    return render(request, 'quiz/quiz-detail.html', context)


def TakeQuiz(request, course_id, module_id, quiz_id):
    quiz = get_object_or_404(Quizzes, id=quiz_id)
    context = {
        'quiz': quiz,
        'course_id': course_id,
        'module_id': module_id,
    }
    return render(request, 'quiz/take-quiz.html', context)


def SubmitAttempt(request, course_id, module_id, quiz_id):
    user = request.user
    quiz = get_object_or_404(Quizzes, id=quiz_id)
    earned_points = 0
    if request.method == 'POST':
        questions = request.POST.getlist('question')
        answers = request.POST.getlist('answer')
        attempter = Attempter.objects.create(user=user, quiz=quiz, score=0)

        for q, a in zip(questions, answers):
            question = Question.objects.get(id=q)
            answer = Answer.objects.get(id=a)
            Attempt.objects.create(
                quiz=quiz, attempter=attempter, question=question, answer=answer)
            Completion.objects.create(user=user, course_id=course_id, quiz_id=quiz_id)
            if answer.is_correct == True:
                earned_points += question.points
                attempter.score += earned_points
                attempter.save()
            return redirect('index')


def AttemptDetail(request, course_id, module_id, quiz_id, attempt_id):
    user = request.user
    quiz = get_object_or_404(Quizzes, id=quiz_id)
    attempts = Attempt.objects.filter(quiz=quiz, attempter__user=user)
    context = {
        'quiz': quiz,
        'attempts': attempts,
        'course_id': course_id,
        'module_id': module_id,
    }
    return render(request, 'quiz/attempt-detail.html', context)

quiz/templates/quiz/attempt-detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="section center-align">
	<h4>{{ quiz.title }} Results</h4>
	<div class="divider"></div>
</div>

<div class="row container">

<div class="col s4">
  <h5>Due:</h5>
  <p>{{ quiz.due }}</p>
</div>

<div class="col s4">
  <h5>Allowed Attempts:</h5>
  <p>{{ quiz.allowed_attempts }}</p>
</div>

<div class="col s4">
  <h5>Time limit (Minutes):</h5>
  <p>{{ quiz.time_limit_mins }}</p>
</div>

<div class="col s12">
  {{ quiz.description | safe }}  
</div>


<div class="col s12">
  <form class="col s12">
    {% csrf_token %}
    {% for question in quiz.questions.all %}
      <div class="col s12">
        <br>
        <p>{{ question.question_text }}</p>
        <input type="hidden" name="question" value="{{ question.id }}">
      </div>
      {% for answer in question.answers.all %}
        <div class="input col s12">
          <label>
            <input name="answer" type="checkbox" value="{{ answer.id }}" {% if answer.is_correct == True %}checked="checked"{% endif %}/>
            <span>{{ answer.answer_text }}</span>
          </label>          
        </div>
      {% endfor %}
    {% endfor %}
  </form>
</div>


<div class="section col s12">
  <h5>Your answers</h5>
  <div class="divider"></div>
  {% for attempt in attempts %}
    <h5 class="{% if attempt.answer.is_correct == True %}green{% else %}red{% endif %}-text"><b>{{ attempt.answer.answer_text }}</b></h5>
  {% endfor %}
</div>


</div>


{% endblock %}

quiz/templates/quiz/new-question.html
{% extends 'base.html'%}

{% block content %}

<div class="row center-align container">
    <div class="col s12">
        <form method="post" enctype="multipart/form-data" action="" role="form">
            {% csrf_token %}
            <h3 class="title is-3">Create New Quiz</h3>
            <div class="input-field col s12">
                {{ form.question_text }}
                <label for="title">Question </label>
            </div>
            <div class="input-field col s12">
                {{ form.points }}
                <label for="points">Marks:</label>
            </div> 
            <div class="input-field col s9">
                <input type="text" name="answer_text" id="id_answer_text" class="validate">
                <label for="title">Answer 1</label>
            </div>
            <div class="input-field col s3">
                <select id="id_is_correct" name="is_correct">
                  <option value="" disabled selected>Choose your yes or no</option>
                  <option value="True">Yes</option>
                  <option value="False">No</option>
                </select>
                <label>Is this the correct answer ?</label>
              </div>
            <div class="input-field col s9">
                <input type="text" name="answer_text" id="id_answer_text" class="validate">
                <label for="title">Answer 2</label>
            </div>
            <div class="input-field col s3">
                <select id="id_is_correct" name="is_correct">
                  <option value="" disabled selected>Choose your yes or no</option>
                  <option value="True">Yes</option>
                  <option value="False">No</option>
                </select>
                <label>Is this the correct answer ?</label>
              </div>
            <div class="input-field col s9">
                <input type="text" name="answer_text" id="id_answer_text" class="validate">
                <label for="title">Answer 3</label>
            </div>
            <div class="input-field col s3">
                <select id="id_is_correct" name="is_correct">
                  <option value="" disabled selected>Choose your yes or no</option>
                  <option value="True">Yes</option>
                  <option value="False">No</option>
                </select>
                <label>Is this the correct answer ?</label>
              </div>
            <div class="input-field col s9">
                <input type="text" name="answer_text" id="id_answer_text" class="validate">
                <label for="title">Answer 4</label>
            </div>
            <div class="input-field col s3">
                <select id="id_is_correct" name="is_correct">
                  <option value="" disabled selected>Choose your yes or no</option>
                  <option value="True">Yes</option>
                  <option value="False">No</option>
                </select>
                <label>Is this the correct answer ?</label>
              </div>

            <div class="col s12">
                <p class="control">
                    <button type="submit" value="Create" class="btn waves-effect waves-light #546e7a blue-grey">
                        Create Question
                    </button>
                </p>
            </div>
            <div class="col s12"> 
                <a href="{% url 'my-courses'%}" class="btn-small waves-effect wave-light #546e7a blue-grey">Finish</a>
                
            </div>

        </form>

    </div>
</div>

{% endblock %}

quiz/templates/quiz/new-quiz.html
{% extends 'base.html'%}

{% block content %}

<div class="row center-align container">
    <div class="col s12">
        <form method="post" enctype="multipart/form-data" action="" role="form">
            {% csrf_token %}
            <h3 class="title is-3">Create New Quiz</h3>
            <div class="input-field col s12">
                {{ form.title }}
                <label for="title">Title</label>
            </div>
            <div class="input-field col s12">
                {{ form.description }}
            </div>
            <div class="input-field col s12">
                {{ form.due }}
                <label for="due">Due</label>
            </div>
            <div class="input-field col s12">
                {{ form.allowed_attempts }}
                <label for="allowed_attempts">Attempts</label>
            </div>
            <div class="input-field col s12">
                {{ form.time_limit_mins }}
                <label for="time_limit_mins">Time Limit in Minutes</label>
            </div>
            <div class="row">
                <div class="col s12">
                    <span style="color: red; font-weight: bold;">{{ form.errors }}</span>
                </div>
            </div>


            <div class="field">
                <p class="control">
                    <button type="submit" value="Create" class="btn waves-effect waves-light #546e7a blue-grey">
                        Create Quiz
                    </button>
                </p>
            </div>

        </form>

    </div>
</div>

{% endblock %}

quiz/templates/quiz/quiz-detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="section">
    <h4 class="center-align">{{quiz.title}}</h4>
    <div class="divider"></div>
</div>
<div class="row container">

    <div class="col s4">
        <h5>Due:</h5>
        <p>{{quiz.due}}</p>
    </div>
    <div class="col s4">
        <h5>Attempts:</h5>
        <p>{{quiz.allowed_attempts}}</p>
    </div>
    <div class="col s4">
        <h5>Time limit (Minutes):</h5>
        <p>{{quiz.time_limit_mins}}</p>
    </div>
    <div class="col s12 ">
        {{quiz.description | safe }}
    </div>

    <div class="fixed-action-btn">
        <a href="{{request.META.HTTP_REFERER}}" class="btn-floating waves-light #546e7a blue-grey"><i class="material-icons">arrow_back</i></a>
    </div>
    <div class="col s12">
        <ul class="collection with-header">
          <li class="collection-header"><h4>My attempts</h4></li>
          {% for attempt in my_attempts %}
            <li class="collection-item">
              <a href="{% url 'attempt-detail' course_id module_id quiz.id attempt.id %}" class="#546e7a blue-grey-text"><h5>Scored: {{ attempt.score }}</h5></a>
            </li>
          {% endfor %}    
        </ul>  
      </div>
    <div class="col s12"> 
        <a href="{% url 'take-quiz' course_id module_id quiz.id %}" class="btn-small waves-effect wave-light #546e7a blue-grey">Take Quiz</a>
        
    </div>
</div>
{%endblock%}

quiz/templates/quiz/take-quiz.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="section">
	<h4>{{ quiz.title }}</h4>
	<div class="divider"></div>
</div>

<div class="row">

<div class="col s4">
  <h5>Due:</h5>
  <p>{{ quiz.due }}</p>
</div>

<div class="col s4">
  <h5>Allowed Attempts:</h5>
  <p>{{ quiz.allowed_attempts }}</p>
</div>

<div class="col s4">
  <h5>Time limit:</h5>
  <p>{{ quiz.time_limit_mins }}</p>
</div>

<div class="col s12">
  {{ quiz.description | safe }}  
</div>


<div class="col s12">
  <form method="post" action="{% url 'submit-quiz' course_id module_id quiz.id %}" role="form" class="col s12">
    {% csrf_token %}
    {% for question in quiz.questions.all %}
      <div class="col s12">
        <br>
        <p>{{ question.question_text }}</p>
        <input type="hidden" name="question" value="{{ question.id }}">
      </div>
      {% for answer in question.answers.all %}
        <div class="input col s12">
          <label>
            <input name="answer" type="checkbox" value="{{ answer.id }}" />
            <span>{{ answer.answer_text }}</span>
          </label>          
        </div>
      {% endfor %}
    {% endfor %}
    <div class="col s12">
        <button type="submit" value="login" class="btn waves-effect waves-light #546e7a blue-grey">
          Submit
        </button>
        
    </div>
  </form>
</div>


</div>


{% endblock %}